[package]
name = "code_highlighter"
version = "0.1.1"
edition = "2021"
description = "Highlights code for printing"
repository = "https://github.com/yazaldefilimone/code_highlighter.rs"
license = "MIT"
keywords = ["console", "terminal", "error"]
categories = ["utils"]

[dependencies]
